version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/project/my-app

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}

      - run:
          name: Print Current Directory
          command: |
            cd my-app
            ls

      - run:
          name: Build SolidJS App
          command: |
            cd my-app
            ls
            npm run build

      - run:
          name: Install Vercel CLI Locally
          command: npm install vercel@latest --save-dev

      - run:
          name: Deploy to Vercel (let Vercel build)
          command: |
            cd my-app
            ls
            npx vercel deploy --prod --yes --token=$VERCEL_TOKEN

workflows:
  deploy:
    jobs:
      - build-and-deploy
