# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  # This job will handle building and deploying our SolidJS app
  build-and-deploy:
    # Specify the execution environment. We'll use a Node.js Docker image
    # as SolidJS is a JavaScript framework.
    docker:
      - image: cimg/node:20.11.0 # Or a more recent stable Node.js version

    # Set the working directory for all steps in this job
    # This assumes your SolidJS app is located in a subdirectory named 'my-app'
    working_directory: ~/project/my-app

    # Steps are a list of commands executed in the job's environment
    steps:
      # Checkout the code from your GitHub repository into the working directory
      # This will checkout into ~/project/ and then the working_directory will change to ~/project/my-app
      - checkout

      # Install project dependencies
      - run:
          name: Install Dependencies
          command: npm install # Or yarn install if you're using Yarn

      # Build the SolidJS application for production
      - run:
          name: Build SolidJS App
          command: npm run build # Or yarn build

      # Add a placeholder for deployment for now.
      # We'll fill this in with Vercel CLI commands in a later step.
      - run:
          name: Placeholder for Vercel Deployment
          command: echo "Deployment step to be added later..."

# Orchestrate jobs using workflows
# Workflows define the order in which jobs run
workflows:
  version: 2
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy