version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.11.0
    working_directory: ~/project/my-app

    steps:
      - checkout

      # Restore npm cache for faster builds
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}

      # Install project dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Save dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}

      # Build the SolidJS project using Vite
      - run:
          name: Build SolidJS App
          command: npm run build

      # Install Vercel CLI
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel@latest

      # Deploy to Vercel using token from environment variable
      - run:
          name: Deploy to Vercel
          command: >
            vercel --prod --confirm --token=$VERCEL_TOKEN

workflows:
  deploy:
    jobs:
      - build-and-deploy
